### ISSUE TITLE
Errors in portal

### ISSUE THREAD

**Issue by paul-ruth** [fabric-testbed/fabric-portal#120]
There are a lot of errors that the user sees in the portal that are over reported.  

For example, when you are searching for a user to add you a project you often get 5-10 error saying the user cannot be found.  This is often because the search is happening every time you add/remove a character from the search box. In this case, we might fix it by only searching when the use hits <enter> or maybe there could be a search button too.  

There are others too. Sometimes there is a token issue and 2-3 error pop up saying something about it.

**Comment by yaxue1123** [comment]
Related issue: https://github.com/fabric-testbed/fabric-portal/issues/129

**Comment by yaxue1123** [comment]
Related issue on orchestrator API: https://github.com/fabric-testbed/OrchestratorClient/issues/18

**Comment by ibaldin** [comment]
Maybe one way to address Paul’s concern is to change the error message to say ‘Unable to obtain authentication token, the likely reason is you are not a member of any projects. Please request to join a project’

**Comment by yaxue1123** [comment]
Portal has changed the UI and workflow in the following aspects to address the issues of portal error messages:

- For adding project member/ owner, a button is added for user to click to trigger the search function;
- For My Slices page, if the user doesn't have a project/ slice yet, show a callout message to guide users to join a project or create a slice first (avoid calling Credential Manager and getting error response due to no project existence).
