### ISSUE TITLE
Feedback on slice creator.

### ISSUE THREAD

**Issue by 842Mono** [fabric-testbed/fabric-portal#183]
I tried the slice creator, and I wanted to share the issues I found.

1. When trying to create a slice, when I click the "create slice" button, I get an error saying "Lease End Time is not in format %Y-$m-$d $H:$M:$S". It seems that something is wrong with the entry of the date of the lease end time.

2. Also, when trying to create a slice, I get an error saying "Error [NetworkX graph error not well-formed (invalid token): line 1, column 0] importing graph". It happens when there is a network card component attached. (One speculation is that the ports of the network card need to be connected to something. Just a guess.)

3. I cannot add a network service. I am not sure how to connect two network interface ports to each other using the network service (ptp, sts, bridge, fabnet...). It asks me to connect the ports by clicking on the graph, but clicking the graph does nothing.

4. I cannot upload a sliver public key. I can only generate one.

5. I cannot add a node without a component. A node has to have at least one component attached. I don't see why that's the case.

And just a quick note about what works. Adding nodes with components works. Selecting a project works. Deleting nodes works. Clearing the slice works. Generating a slice ssh keypair, and selecting it, works.

**Comment by yaxue1123** [comment]
Hi Mina @842Mono , thanks for providing your feedback!

- 1 & 2: the issues should be gone. Beta orchestrator was running v1.1 to test upgrade at the time you were trying to create slices thus causing these errors.
- 3:  You need click on the connection point (grey square inside NICs) then click "Select", the selected connection points will be shown as a list in the "Step 4: Add Network Service" panel. For more information, Please refer to [this knowledge base article](https://learn.fabric-testbed.net/knowledge-base/portal-slice-builder-user-guide/) for the step-by-step guide of using portal slice builder. The newer version of portal also includes this link near the "New Slice" header on slice builder page.
- 4: I tried the uploading public key function and it works as expected. I'll update the toast message to include the exact error message the User Information Service API returns so that users can see why the request failed.
- 5: The current version of slice builder requires at least one component in the VM node. This is [an issue to be resolved before next release](https://github.com/fabric-testbed/fabric-portal/issues/178). Sorry for the inconvenience brought to you.

Thanks again for your help and feedback!

**Comment by 842Mono** [comment]
Hi. Thank you for your reply. I am now able to create slices. So thanks!

There's one more issue however. Slices I create go from "configuring" to "dead", or sometimes to "closing". And there's no way for me to find out what went wrong. For example, the problem can be "insufficient resources" on the site say. How can I find out what went wrong?

As for 4, uploading sliver public key, this is the error I get, below.

![image](https://user-images.githubusercontent.com/10537473/172985236-e38a7b82-b3a2-4f6b-905e-4469c977a06f.png)

And this is an example key that I try to upload.

`ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABegFVxlpYv8+iImL9i2gy3JR20XZAy+OzEEyejZhN2au9Id2eddP34n64rnm5fguhaV2VHAWLUhZHE4QdWmVrgUy1LGJKjS8uZ1hWNE4AGqchfqgMWjLmoO7LP/PW/sa9ACEAqMesGtQYSR0dAvtSkPBtlX4UYQAR3VZ+gYt+XvN+iU8JsztiAedEn2QMBVPUTPM6vKqHkFRa4kwKYjtEleU2rl1WVqMxD5vrkxBrZ5x5oVKNuFY3M8kQN1UZvPXVlkHghqfb0uBKoJLnCmLgHfBD5uCp1UGcjmUmFGrkTHFydCSifhhr0DDKgIAOj6dGPv7PgoRg1C4F8ExUXXQcQKopnxIXzrwr9D6LJnJ/bjkarE/UzAK6+4qtaYbsasr8EZWXNqiw85Re6Z5vXihYj6cohzMJAsSO89+CbnN91fa8Jv/C/enfmDmdC326x4ir8iPDRTrizTjMrLkGJOvwVU5Jm9M+GafnTqNz4ounIUylFWBTeyybVk/96w== fabric@jupyter-minawm-40bu-2eedu`

The command to generate it was, as described: `ssh-keygen -t rsa -b 3017`

**Comment by yaxue1123** [comment]
Hi Mina,

Thanks for your feedback! The issues you mentioned are really insightful and matter to us!

- About the usability issue you mentioned that slices states changes without details revealed, I'll bring this up in our team meeting next week and discuss about future API support.
- As for the ssh key upload error, I tried with your example key and saw the error detail as `Provided key for 6744e0c2-745b-4f41-9746-deb039fb00a0 is invalid due to SSH Key exception: Provided RSA public key length 3017 is not satisfactory` from browser inspector tool -> Network. This is a usability issue portal will fix soon to show the exact detailed error message instead of a general "Bad Request" message. 

Please feel free to tell us any other functional/ usability concerns you have in Github issues or learn site forums. Thanks again for your time and help!

Yaxue

**Comment by 842Mono** [comment]
Hi. Okay. I just keep on trying things. I caught one more thing. I left the slice creator tab open and came back later. It gets stuck in a funny looking loop haha 😄, here's a quick video https://www.youtube.com/watch?v=0Qh8v44mL6Y . Not sure if you can get this behavior on your machine. But I just thought I'd report.

One more small detail. The lease end time gets set to the current time. I guess it might be better if it gets set to the current time plus one day or plus seven days.

By the way, I was able to upload a public key. I made a `-b 4096` key and it worked. I used a 3017 key instead of a 3072 key. My mistake. An error message would be helpful in any case.

Thanks!

**Comment by yaxue1123** [comment]
Hi Mina, 

The issues you mentioned in the previous reply have been addressed. 

- slice builder stuck in loop: when portal is idle for a while, the credential is expired thus resulting in the API calls failure. I've update the slice builder to logout when such situation occurs. And will enhance usability by [adding a session timeout modal](https://github.com/fabric-testbed/fabric-portal/issues/136). 
- The default lease end time is set to current time plus 24 hours per your suggestion. 

Thanks for your useful suggestions!

Best,
Yaxue
